# Generated by Django 3.1.6 on 2021-02-22 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='user_email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='msg',
            new_name='user_msg',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='subject',
            new_name='user_subject',
        ),
    ]
